const products = [
  {
    id: '1',
    name: 'HeadPhone',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    image: '/images/airpods.jpg',
    brand: 'Brand X',
    category: 'Category 1',
    price: 49.99,
    rating: 4.5,
    numreviews: 25,
    countinstock: 10,
  },
  {
    id: '2',
    name: 'Laptop',
    description:
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    image: '/images/airpods.jpg',
    brand: 'Brand Y',
    category: 'Category 2',
    price: 29.99,
    rating: 3.8,
    numreviews: 15,
    countinstock: 75,
  },
  {
    id: '3',
    name: 'Product C',
    description:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: '/images/airpods.jpg',
    brand: 'Brand Z',
    category: 'Category 1',
    price: 69.99,
    rating: 4.2,
    numreviews: 30,
    countinstock: 50,
  },
  {
    id: '4',
    name: 'Product C',
    description:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: '/images/mouse.jpg',
    brand: 'Brand Z',
    category: 'Category 1',
    price: 69.99,
    rating: 4.2,
    numreviews: 30,
    countinstock: 50,
  },
  {
    id: '5',
    name: 'Product C',
    description:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: '/images/phone.jpg',
    brand: 'Brand Z',
    category: 'Category 1',
    price: 69.99,
    rating: 4.2,
    numreviews: 30,
    countinstock: 50,
  },
  {
    id: '6',
    name: 'Product C',
    description:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: '/images/playstation.jpg',
    brand: 'Brand Z',
    category: 'Category 1',
    price: 69.99,
    rating: 4.2,
    numreviews: 30,
    countinstock: 50,
  },
  {
    id: '7',
    name: 'Product C',
    description:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: '/images/sample.jpg',
    brand: 'Brand Z',
    category: 'Category 1',
    price: 69.99,
    rating: 4.2,
    numreviews: 30,
    countinstock: 50,
  },
  {
    id: '8',
    name: 'Product C',
    description:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: '/images/screens.png',
    brand: 'Brand Z',
    category: 'Category 1',
    price: 69.99,
    rating: 4.2,
    numreviews: 30,
    countinstock: 50,
  },
  {
    id: '9',
    name: 'Product C',
    description:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: '/images/airpods.jpg',
    brand: 'Brand Z',
    category: 'Category 1',
    price: 69.99,
    rating: 4.2,
    numreviews: 30,
    countinstock: 50,
  },
  {
    id: '10',
    name: 'Product C',
    description:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: '/images/camera.jpg',
    brand: 'Brand Z',
    category: 'Category 1',
    price: 69.99,
    rating: 4.2,
    numreviews: 30,
    countinstock: 50,
  },
];

export default products;
